all: sessionui.rc konsoleui.rc

sessionui.rc:
	wget 'https://raw.githubusercontent.com/KDE/konsole/master/desktop/sessionui.rc'

konsoleui.rc:
	wget 'https://raw.githubusercontent.com/KDE/konsole/master/desktop/konsoleui.rc'

clean:
	rm -f sessionui.rc
	rm -f konsoleui.rc
